language: php
services:
  - mysql
branches:  
  only:
  - master
  - dev
php:
  - '5.5'  
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"  
  - sudo echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config  
  - ssh-keyscan -H -t rsa,dsa github.com >> ~/.ssh/known_hosts
  - sudo git clone -b BRANCH https://github.com/astroanu/collejo-tests.git tests
  - sudo git rev-parse HEAD
  - sudo cp tests/phpunit.xml.sample phpunit.xml
  - sudo cp tests/env.travis.sample .env
  - rm -R database
  - sudo git clone -b BRANCH https://github.com/astroanu/collejo-db-fatories.git database
  - sudo git rev-parse HEAD
  - sudo chmod -R 755 database
  - composer install
  - composer dump-autoload
  - mysql -e 'create database test;'  
  - sudo php artisan migrate:copy
  - sudo chmod -R 755 storage bootstrap/cache
  - composer dump-autoload -o
